[[requests]]
name = "Get Access Token"
method = "POST"
url = "https://accounts.spotify.com/api/token"
[requests.body]
type = "Form"
grant_type = "client_credentials"
[requests.headers]
"Authorization" = "Basic {client_credentials_base64}"
[requests.dependencies.client_credentials_base64]
source = "EnvVar"
name = "SPOTIFY_CLIENT_CREDENTIALS"
prompt = "Enter your Base64-encoded Client ID and Secret"

[[requests]]
name = "Get User Playlists"
method = "GET"
url = "https://api.spotify.com/v1/me/playlists"
[requests.headers]
"Authorization" = "Bearer {access_token}"
[requests.dependencies.access_token]
source = "Response"
request = "Get Access Token"
target = { source = "JsonBody", pointer = "/access_token" }

