[[requests]]
name = "Get Charges"
method = "GET"
url = "https://api.stripe.com/v1/charges"
[requests.headers]
"Authorization" = "Bearer {api_key}"
[requests.dependencies.api_key]
source = "EnvVar"
name = "STRIPE_API_KEY"
prompt = "Enter your Stripe API Key"

