[[requests]]
name = "Get Current Weather"
method = "GET"
url = "https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}"
[requests.headers]
"Accept" = "application/json"
[requests.dependencies.city]
source = "EnvVar"
name = "CITY"
prompt = "Enter the city name"
[requests.dependencies.api_key]
source = "OnePassword"
vault = "Private"
item = "OpenWeather"
field = "api-key"

[[requests]]
name = "Get 5-Day Forecast"
method = "GET"
url = "https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
[requests.headers]
"Accept" = "application/json"
[requests.dependencies.lat]
source = "Response"
request = "Get Current Weather"
target = { source = "JsonBody", pointer = "/coord/lat" }
[requests.dependencies.lon]
source = "Response"
request = "Get Current Weather"
target = { source = "JsonBody", pointer = "/coord/lon" }
[requests.dependencies.api_key]
source = "OnePassword"
vault = "Private"
item = "OpenWeather"
field = "api-key"
